field: e957dcea-d4db-492e-b646-db2744f33af3 # Page Content
fieldLayouts:
  e2a005e2-78d6-4bc1-88d6-f4ca0cecbf83:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d6ddbc26-545f-4a2f-8e41-91414463775f # Photo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c6714db-5251-4725-8efc-eda8699e4d88
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9bbaa755-0aa5-482b-b0fc-f0441e1a8101 # Full name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa521b88-54ae-4ece-9e77-10c05c6c3c5f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5a95b1ec-78da-4fdf-877b-3642ff46dda1 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05da6d62-9070-45b7-94f1-e4aec1454c58
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 79de4361-fcca-4120-9200-00ebcad0622c
        userCondition: null
fields:
  5a95b1ec-78da-4fdf-877b-3642ff46dda1: # Description
    columnSuffix: iqbxplcb
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: null
    name: Description
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 2
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9bbaa755-0aa5-482b-b0fc-f0441e1a8101: # Full name
    columnSuffix: negjktnv
    contentColumnType: text
    fieldGroup: null
    handle: fullName
    instructions: null
    name: 'Full name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d6ddbc26-545f-4a2f-8e41-91414463775f: # Photo
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: photo
    instructions: null
    name: Photo
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:36f4d8c6-ae78-48e7-bcad-1c1509e6750f' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:36f4d8c6-ae78-48e7-bcad-1c1509e6750f' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: trainers
name: Trainers
sortOrder: 4
