defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  dc2a2269-f434-4973-af9f-1342311544c2: # rwgym
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
